# Generated by Django 3.2.5 on 2022-04-30 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='store_pickle',
            field=models.FileField(default='null', upload_to=''),
            preserve_default=False,
        ),
    ]
